import ContentLayout from "@/components/contentLayout";
import NewStockProcess from "@/components/newStockProcess";
import ToolBar from "@/components/toolBar";

export default function AutomaticMethodPage() {
  const status: number[] = [2, 1, 0];
  return (
    <ContentLayout>
      {{
        title: "New stock",
        process: <NewStockProcess status={status} />,
        description: [
          "The product list will be generated by the system, which may take some time.",
          "Once the list is ready, you can consult it and modify it if necessary."
        ],
        subtitle: "List of products",
        content: (
          <>
            <ToolBar />
          </>
        )
      }}
    </ContentLayout>
  );
}
